Repository caicloud/cyclone-website, pull requests merged in 2019-05, with the labels that each got.

#1 chore(*): add owners file
  OWNERS
Labels: caicloud-cla: yes, release-note-none, size/S

#3 首页
  .gitignore
  404.html
  Gemfile
  Gemfile.lock
  _config.yml
  _includes/disqus_comments.html
  _includes/footer.html
  _includes/google-analytics.html
  _includes/head.html
  _includes/header.html
  _includes/icon-github.html
  _includes/icon-github.svg
  _includes/icon-twitter.html
  _includes/icon-twitter.svg
  _includes/social.html
  _layouts/default.html
  _layouts/home.html
  _layouts/page.html
  _layouts/post.html
  _posts/2019-05-07-welcome-to-jekyll.md
  _sass/minima.scss
  _sass/minima/_base.scss
  _sass/minima/_layout.scss
  _sass/minima/_syntax-highlighting.scss
  _sass/minima/docs.scss
  _sass/minima/index.scss
  _sass/minima/media.scss
  assets/images/banner.jpg
  assets/images/co1.png
  assets/images/co2.png
  assets/images/co3.png
  assets/images/co4.png
  assets/images/f1.png
  assets/images/f10.png
  assets/images/f2.png
  assets/images/f3.png
  assets/images/f4.png
  assets/images/f5.png
  assets/images/f6.png
  assets/images/f7.png
  assets/images/f8.png
  assets/images/f9.png
  assets/images/ic_close_normal.png
  assets/images/ic_menu_normal.png
  assets/images/logo-f.png
  assets/images/logo.png
  assets/images/logo_f_i.ico
  assets/js/index.js
  assets/js/jquery.min.js
  assets/main.scss
  blog/index.html
  community.html
  docs.html
  index.md
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XXL

#4 Add more pages
  404.html
  README.md
  _config.yml
  _includes/footer.html
  _includes/header.html
  _layouts/home.html
  _layouts/post.html
  _posts/2019-05-07-welcome-to-jekyll.md
  _posts/2019-2-23-welcome-to-jekyll.md
  _sass/minima.scss
  _sass/minima/_base.scss
  _sass/minima/_layout.scss
  _sass/minima/docs.scss
  _sass/minima/index.scss
  _sass/minima/media.scss
  assets/images/20190223.jpg
  assets/js/index.js
  blog/index.html
  community.html
  docs.html
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/L

#5 Fix css and js caches
  _config.yml
  _includes/footer.html
  _includes/head.html
  _sass/minima/_layout.scss
  _sass/minima/docs.scss
  _sass/minima/media.scss
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/S

#7 fix: fix errors in roadmap
  _config.yml
Labels: approved, caicloud-cla: yes, lgtm, release-note-none, size/XS
